name: Move PR to "In Pull Request"

on:
  pull_request:
    types: [opened]

jobs:
  update-project-board:
    runs-on: ubuntu-latest
    steps:
      - name: Move PR to "In Pull Request"
        uses: actions/add-to-project@v0.1.0
        with:
          project-url: "https://github.com/orgs/DeveloperAcademy-POSTECH/projects/163"
          column-name: "In Pull Request"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
